###############################################################################
# 
# Filename: main.yml
# Description: github-actions workflow definition
# 
# For more information see:
#   - https://docs.github.com/en/free-pro-team@latest/actions/guides
#
###############################################################################

name: Build Development Environment

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/developer:$GITHUB_SHA
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_USERNAME }}/development
      #     tag_with_ref: true
